### ISSUE TITLE
High Performance OTDE?

### ISSUE THREAD

**Issue by JZL** [oseminck/tree_order_evaluation#1]
Hi,

Thanks for your really nice paper! Very readable and exactly what I was looking for. I was trying to applying your code to a somewhat larger graph (~5000 nodes), and ran into some issues. 

Jumping right in and working through the slow points on a flame graph, I happily `numba`-ified `clusterCrossings` to be much faster (and am happy to share the code, it's mostly syntactical). But then got limited by the recursion on `allPermutations` and as I started to step through the code, other recursive elements started to worry me for this large of a graph.

Do you think it is feasible to run this on that large of a graph? I can throw pretty large amounts of CPU and memory at the problem since I only need to do it once for this graph and only need the reordered elements, not the nodes to be deleted/etc. Or are you aware of a high performance of this algorithm/`[10]/[22]`'s. The `O(n log n)` theoretical runtime is so alluring I was hoping it would be able to run :-)

Maybe [OGDF's crossing minimization for plotting](https://ogdf.github.io/doc/ogdf/group__gd-layered-crossmin.html)? Any thoughts at all would be appreciated. I understand Dr. Gambette is the corresponding author so I can instead ask him.

Thanks
Jonah

**Comment by oseminck** [comment]
Dear Jonah, I will transfer your question to Philippe Gambette and Laurent Bulteau who could give better answers than I can. I come back to you as soon as possible.

**Comment by JZL** [comment]
Hi,

Wow thanks for your amazingly prompt response! That sounds great :-) I'm happy to continue over email if that's easier

Cheers
Jonah

**Comment by JZL** [comment]
Just as a note for other people looking for fast-running code, I found the dynamic programming methods very scalable, especially when re-implementing in other languages like julia where you can memoize more easily and where for-loops are fast. Even if the memory is $N^2$ and worst case compute is also polynomial, a dense 100k x 100k matrix is very doable in practice on cloud computing and it only takes like <=5-10 mins to optimize. The cited Venkatachalam et al. paper has some simpler dynamic programming alternatives (section 3.2) which are still very effective.

Thanks again for responding and writing such an easy to read paper!
